CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY ,
    name TEXT NOT NULL, 
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    
)

CREATE TABLE IF NOT EXISTS cars (
    id SERIAL PRIMARY KEY ,
    name TEXT NOT NULL, 
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    img TEXT NOT NULL
)